<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/INTEGRACION_CONT/COLEGIO/BS_CONSULTA" name="BS_CONSULTA-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="BS_CONSULTA.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/INTEGRACION_CONT/COLEGIO/BS_CONSULTA"/>
    <wsdl:binding name="BS_CONSULTA_ptt-binding" type="bs:BS_CONSULTA_ptt" xmlns:bs="http://xmlns.oracle.com/pcbpel/adapter/db/INTEGRACION_CONT/COLEGIO/BS_CONSULTA">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="BS_CONSULTA">
            <soap:operation soapAction="BS_CONSULTA"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>