<wsdl:definitions name="BS_ESTUDIANTES" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/INTEGRACION_CONT/COLEGIO/BS_ESTUDIANTES" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/INTEGRACION_CONT/COLEGIO/BS_ESTUDIANTES" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/BS_ESTUDIANTES" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="BS_ESTUDIANTES_plt">
    <plt:role name="BS_ESTUDIANTES_role">
      <plt:portType name="tns:BS_ESTUDIANTES_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/BS_ESTUDIANTES" schemaLocation="../Schemas/BS_ESTUDIANTES_sp.xsd"/>
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="BS_ESTUDIANTES_ptt">
        <wsdl:operation name="BS_ESTUDIANTES">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>